In [2]:
from __future__ import print_function # python 2, 3의 호환성 문제를 해결하기 위함
import torch      # gradient가 되는 numpy

In [4]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [7]:
x = torch.rand(5,3)
print(x)

tensor([[0.2632, 0.0819, 0.6483],
        [0.7266, 0.5451, 0.3834],
        [0.6326, 0.4443, 0.6000],
        [0.7596, 0.2128, 0.9050],
        [0.6897, 0.2216, 0.9296]])


In [8]:
# 가장 많이 씀 - 0 또는 1 넣고 2 넣고..?
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [15]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

## 앞 사이즈에 맞는 랜덤 노이즈를 넣을 수 있음
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.0239, 0.4565, 0.1672],
        [0.0846, 0.3476, 0.2069],
        [0.4699, 0.7279, 0.9820],
        [0.6323, 0.4841, 0.4841],
        [0.8176, 0.8008, 0.1422]])


In [17]:
x.size()

torch.Size([5, 3])

In [21]:
# Operation
y = torch.rand(5,3)
print(x + y) # element add
print(torch.add(x,y))
print(y.add_(x)) # add x to y

result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[0.2967, 0.7305, 0.3119],
        [0.7259, 0.7397, 0.4544],
        [1.1878, 1.0925, 1.2517],
        [1.5434, 1.1341, 0.9990],
        [1.3500, 1.6207, 0.1664]])
tensor([[0.2967, 0.7305, 0.3119],
        [0.7259, 0.7397, 0.4544],
        [1.1878, 1.0925, 1.2517],
        [1.5434, 1.1341, 0.9990],
        [1.3500, 1.6207, 0.1664]])
tensor([[0.2967, 0.7305, 0.3119],
        [0.7259, 0.7397, 0.4544],
        [1.1878, 1.0925, 1.2517],
        [1.5434, 1.1341, 0.9990],
        [1.3500, 1.6207, 0.1664]])
tensor([[0.3206, 1.1870, 0.4791],
        [0.8105, 1.0872, 0.6613],
        [1.6577, 1.8204, 2.2337],
        [2.1758, 1.6182, 1.4831],
        [2.1676, 2.4215, 0.3086]])


In [26]:
print(x)

tensor([[0.0239, 0.4565, 0.1672],
        [0.0846, 0.3476, 0.2069],
        [0.4699, 0.7279, 0.9820],
        [0.6323, 0.4841, 0.4841],
        [0.8176, 0.8008, 0.1422]])


In [25]:
print(x[:1])
print(x[1:])
print(x[:,1])

tensor([[0.0239, 0.4565, 0.1672]])
tensor([[0.0846, 0.3476, 0.2069],
        [0.4699, 0.7279, 0.9820],
        [0.6323, 0.4841, 0.4841],
        [0.8176, 0.8008, 0.1422]])
tensor([0.4565, 0.3476, 0.7279, 0.4841, 0.8008])


In [30]:
x = torch.randn(4,4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1,8) # -1은 다른 차원으로 채워줌 
print(z.shape)

tensor([[-1.1221, -1.8340,  1.5816,  1.4987],
        [-0.0022,  1.6518,  0.2043,  0.1988],
        [ 0.7873, -0.1361, -0.3168, -1.3651],
        [-1.4518, -0.3094, -0.7840,  1.7885]])
tensor([-1.1221, -1.8340,  1.5816,  1.4987, -0.0022,  1.6518,  0.2043,  0.1988,
         0.7873, -0.1361, -0.3168, -1.3651, -1.4518, -0.3094, -0.7840,  1.7885])
torch.Size([2, 8])


In [33]:
x = torch.randn(1)
print(x)
print(x.item()) # tensor에서 value 꺼낼 때, python numner

tensor([1.2603])
1.2603446245193481


In [37]:
import numpy as np
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [38]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [41]:
np.add(a,1,out=a)

array([2., 2., 2., 2., 2.])

In [42]:
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
